### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Murtazaaly01** [yashoswalyo/MERGE-BOT#17]
Can you add features of muxing audio :). Plz

**Comment by yashoswalyo** [comment]
Do you want multiple audios or, 1 video 1 audio?

**Comment by Murtazaaly01** [comment]
> Do you want multiple audios or, 1 video 1 audio?

Multiple, if there is already one audio in video nd i want to add one more..

**Comment by yashoswalyo** [comment]
#27 Closes this
