### ISSUE TITLE
Issue while Video+Subtitles Merging 

### ISSUE THREAD

**Issue by hotmoon6** [yashoswalyo/MERGE-BOT#33]
It cannot be Merge Video and Subtitles...It works till the Downloaing the inputs and Merging too but in final step it Results an Error 🔄 Renaming Video and strucks...It shows in logs

if UPLOAD_TO_DRIVE[f"{cb.from_user.id}"]:
NameError: name 'UPLOAD_TO_DRIVE' is not defined

I Kept upload as Telegram but it asking Upload to Drive
So, please resolve the bug... its an impressive work thank you sir

**Comment by yashoswalyo** [comment]
Fixed now, Redeploy
It was an import error for `UPLOAD_TO_DRIVE` variable
