### ISSUE TITLE
400 FILE_REFERENCE_EXPIRED

### ISSUE THREAD

**Issue by aakash2021-cap** [yashoswalyo/MERGE-BOT#40]
400 FILE_REFERENCE_EXPIRED - The file id contains an expired file reference, you must obtain a valid one by fetching the message from the origin context (caused by "upload.GetFile")

Bot says :MERGED VIDEO IS CORRUPTED

**Comment by yashoswalyo** [comment]
Uploading to drive?

**Comment by aakash2021-cap** [comment]
No bro

To telegram only

**Comment by yashoswalyo** [comment]
do `/deletethumbnail` once

**Comment by aakash2021-cap** [comment]
Okay let's try

**Comment by aakash2021-cap** [comment]
⭕ Merged Video is corrupted

**Comment by yashoswalyo** [comment]
> ⭕ Merged Video is corrupted
is it showing file reference expired in logs?

**Comment by MuLTiboti** [comment]
> > o Merged Video is corrupted
> 
> is it showing file reference expired in logs?

Yes. Bro

**Comment by aakash2021-cap** [comment]
Yes bro

**Comment by yashoswalyo** [comment]
Your thumbnail file is old @aakash2021-cap

**Comment by aakash2021-cap** [comment]
Done
